"use client";

// GENERATED by @kitn.ai/blocks from assistant.html and assistant.controller.ts.
// It is your code now: edit freely, and regenerate to start over.
import { ConversationItem, Conversations, Empty, ModelSwitcher, PromptInput, Thread } from '@kitn.ai/ui/react';
import { X } from 'lucide-react';
import { useAssistant } from './useAssistant';
import { formatApproxTokens } from './assistant.controller';
import { DocPreview } from './DocPreview';
import './assistant.css';

export function Assistant() {
  const { state, actions, refs } = useAssistant();

  // Generated-file links render as plain <a href="/api/files/..."> inside the
  // kai-message shadow DOM — composedPath() finds the real origin element
  // past shadow retargeting, which a plain event.target can't.
  const handleThreadClick = (event: React.MouseEvent) => {
    const anchor = event.nativeEvent
      .composedPath()
      .find((el): el is HTMLAnchorElement => el instanceof HTMLAnchorElement);
    if (!anchor) return;
    const href = anchor.getAttribute('href');
    if (!href || !href.startsWith('/api/files/')) return;
    event.preventDefault();
    actions.openFilePreview(href, anchor.textContent ?? 'document');
  };

  const handleDelete = (event: React.MouseEvent, id: string, title: string) => {
    event.stopPropagation();
    if (!window.confirm(`Delete "${title}"? This also removes its generated files and can't be undone.`)) return;
    void actions.deleteConversation(id);
  };

  return (
    <div className={state.previewFile ? 'app with-preview' : 'app'}>
      {/* The rail in ITEM mode (the documented consumer-owned loop): the
           rows are the block's own, so the built-in search box filters
           nothing by itself and the block does the filtering in State. */}
      <Conversations
        id="conversations"
        className="rail"
        theme="light"
        activeId={state.activeId}
        onConversationSelect={actions.openConversation}
        onNewChat={actions.newChat}
        onSearch={actions.search}
      >
        {state.conversationRows.map((row) => (
          <ConversationItem key={row.id} conversationId={row.id} unread={row.unread}>
            <span>
              {row.title}
            </span>
            <span slot="meta" hidden={row.previewHidden}>
              {row.preview}
            </span>
            <span slot="menu" className="row-menu">
              <span className="row-time">{row.time}</span>
              <button
                className="row-delete"
                aria-label={`Delete "${row.title}"`}
                onClick={(e) => handleDelete(e, row.id, row.title)}
              >
                <X size={13} />
              </button>
            </span>
          </ConversationItem>
        ))}
      </Conversations>
      <main className="main">
        <header className="topbar">
          <h1>
            Assistant
          </h1>
          {/* The model switcher recipe: a standalone leaf element with no
               navigation anywhere near it. Models in as a JS property,
               selection out via kai-model-change. */}
          <ModelSwitcher
            id="models"
            theme="light"
            models={state.models}
            currentModel={state.currentModel}
            onModelChange={actions.modelChange}
          />
        </header>
        <div className="thread-wrap" onClick={handleThreadClick}>
          <Thread id="thread" theme="light" messages={state.messages} loading={state.loading}>
            <Empty slot="empty" emptyTitle="What can I help with?" description="Ask anything, or start from a suggestion below." />
          </Thread>
        </div>
        {state.loadingStats ? (
          <div className="loading-stats">
            {state.loadingStats.elapsedSeconds}s · ↓ {formatApproxTokens(state.loadingStats.approxTokens)} tokens
          </div>
        ) : null}
        <PromptInput
          id="prompt"
          theme="light"
          placeholder="Ask anything"
          ref={(el) => { refs.current.prompt = el; }}
          suggestions={state.suggestions}
          loading={state.loading}
          stoppable
          onStop={actions.stop}
          triggers={state.promptTriggers}
          onSubmit={actions.submit}
        />
      </main>
      {state.previewFile ? (
        <DocPreview
          url={state.previewFile.url}
          filename={state.previewFile.filename}
          onClose={actions.closeFilePreview}
        />
      ) : null}
    </div>
  );
}
