// GENERATED by @kitn.ai/blocks: the react adapter.
// useSyncExternalStore takes exactly the getter + subscribe pair the
// controller contract specifies, so this file is the whole adapter: no
// state mirrored, no effect re-deriving anything.
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import type { RefObject } from 'react';
import {
  createController,
  type AssistantActions,
  type AssistantRefs,
  type AssistantState,
} from './assistant.controller';

export interface UseAssistant {
  state: AssistantState;
  actions: AssistantActions;
  refs: RefObject<AssistantRefs>;
}

export function useAssistant(): UseAssistant {
  // The refs object is stable and the controller reads it lazily, which is
  // why deps.refs is a getter: here the handles are still null.
  const refs = useRef<AssistantRefs>({ prompt: null });
  const [controller] = useState(() => createController({ refs: () => refs.current }));
  const state = useSyncExternalStore(controller.subscribe, controller.state, controller.state);

  useEffect(() => {
    void controller.actions.boot();
  }, [controller]);

  return { state, actions: controller.actions, refs };
}
